package sur.softsurena.entidades;

import java.sql.Timestamp;
import lombok.Getter;
import lombok.NonNull;
import lombok.experimental.SuperBuilder;

@SuperBuilder
@Getter
public class Analisis {
    private final int id;
    @NonNull private final int id_doctor;
    @NonNull private final int id_paciente;
    @NonNull private final Timestamp fecha_hora_creada;
    @NonNull private final Timestamp fecha_hora_vista;
    @NonNull private final Boolean T_BHCG;
    @NonNull private final Boolean T_EMB_ORINA;
    @NonNull private final Boolean T_EMB_SANGRE;
    @NonNull private final Boolean T_ANT_AUSTRALIANO_BBSAG;
    @NonNull private final Boolean T_CLAMIDIA_IGA;
    @NonNull private final Boolean T_FTA_ABS;
    @NonNull private final Boolean T_HIV;
    @NonNull private final Boolean T_VDRL;
    @NonNull private final Boolean T_ACIDO_URICO;
    @NonNull private final Boolean T_ANT_FEBRILES;
    @NonNull private final Boolean T_ASO_LATEX;
    @NonNull private final Boolean T_BILIRRUBINA;
    @NonNull private final Boolean T_COLESTEROL_TOTAL;
    @NonNull private final Boolean T_COLESTEROL_HDL;
    @NonNull private final Boolean T_COLESTEROL_HDL_LDL;
    @NonNull private final Boolean T_COPROLOGICO;
    @NonNull private final Boolean T_CREATININA_SUERO;
    @NonNull private final Boolean T_CULTIVO_FARINGE;
    @NonNull private final Boolean T_CULTIVO_HECES;
    @NonNull private final Boolean T_CULTIVO_HERIDA_AEROBICO;
    @NonNull private final Boolean T_CULTIVO_OIDO;
    @NonNull private final Boolean T_CULTIVO_SANGRE;
    @NonNull private final Boolean T_CULTIVO_SEMEN;
    @NonNull private final Boolean T_CULTIVO_URETRA;
    @NonNull private final Boolean T_CULTIVO_VAGINA;
    @NonNull private final Boolean T_ELECTRO_HEMOGLOBINA;
    @NonNull private final Boolean T_ERITROSEDIMENTACION;
    @NonNull private final Boolean T_ESPERMATOGRAMA;
    @NonNull private final Boolean T_ESTRADIOL;
    @NonNull private final Boolean T_ESTROGENO_TOTALES;
    @NonNull private final Boolean T_FACTOR_REUMATOIDE;
    @NonNull private final Boolean T_FALCEMIA;
    @NonNull private final Boolean T_FOSFATASA_ALCALINA;
    @NonNull private final Boolean T_FSH;
    @NonNull private final Boolean T_GLICEMIA;
    @NonNull private final Boolean T_HEMOGLO_GLUCOSILADA;
    @NonNull private final Boolean T_HEMOGRAMA;
    @NonNull private final Boolean T_HEPATITIS_A;
    @NonNull private final Boolean T_HEPATITIS_C;
    @NonNull private final Boolean T_KOH;
    @NonNull private final Boolean T_LH;
    @NonNull private final Boolean T_ORINA;
    @NonNull private final Boolean T_PCR;
    @NonNull private final Boolean T_PROGESTERONA;
    @NonNull private final Boolean T_PROLACTINA;
    @NonNull private final Boolean T_PROTEINAS_TOTALES;
    @NonNull private final Boolean T_PSA_TOTAL;
    @NonNull private final Boolean T_PSA_LIBRE;
    @NonNull private final Boolean T_SANG_OCULT_HECES;
    @NonNull private final Boolean T_SGOT_TGO;
    @NonNull private final Boolean T_SGOT_TGP;
    @NonNull private final Boolean T_T3;
    @NonNull private final Boolean T_T4;
    @NonNull private final Boolean T_T4_LIBRE;
    @NonNull private final Boolean T_COOMBS_DIRECTO;
    @NonNull private final Boolean T_COOMBS_INDIRECTO;
    @NonNull private final Boolean T_TESTOSTERONA;
    @NonNull private final Boolean T_TIPIFICACION_SANGUINEA;
    @NonNull private final Boolean T_TOXOPLAS_IGG;
    @NonNull private final Boolean T_TOXOPLAS_IGM;
    @NonNull private final Boolean T_TRIGLICERIDOS;
    @NonNull private final Boolean T_TSH;
    @NonNull private final Boolean T_TUBERCULINA;
    @NonNull private final Boolean T_UREA;
    private final String OTROS;
    private final String USUARIO;
    private final String ROL;
}